export enum JobType {
    CHANNEL_POLICY_CLEAR,
    CHANNEL_POLICY_SET,
    JOB_MESSAGE_CREATE_SCHEDULE_SET,
    JOB_MESSAGE_CREATE_SCHEDULE_CLEAR,
    MESSAGE_CREATE,
    MESSAGE_RETRY,
    MESSAGE_RELEASE,
    MESSAGE_SWEEP_MANY,
    MESSAGE_UNLOCK
}
