export const MESSAGE_PRIORITY = null
export const MESSAGE_NUM_ATTEMPTS = 1
export const MESSAGE_TIMEOUT_SECS = 60 * 5
export const MESSAGE_STALE_SECS = 60 * 60

export const DAEMON_PROCESSOR_EXECUTION_CONCURRENCY = 1
export const DAEMON_PROCESSOR_QUEUE_PREFIX = ''
export const DAEMON_PROCESSOR_TIMEOUT_SECS = 2
export const DAEMON_ORCHESTRATOR_UNLOCK_TIMEOUT_SECS = 2
export const DAEMON_ORCHESTRATOR_SCHEDULE_TIMEOUT_SECS = 2
export const DAEMON_ORCHESTRATOR_CLEAN_TIMEOUT_SECS = 60

export const SCHEDULE_SLIPPAGE_MINS = 60
