export const MESSAGE_DEFAULT_PRIORITY = null
export const MESSAGE_DEFAULT_NAME = null
export const MESSAGE_DEFAULT_PROCESSING_MS = 60 * 60 * 1_000
export const MESSAGE_DEFAULT_DELAY_MS = 0
export const DAEMON_PROCESSOR_DEFAULT_EXECUTION_SLOTS = 1
export const DAEMON_PROCESSOR_DEFAULT_TIMEOUT_MS = 1000
export const DAEMON_SCHEDULER_DEFAULT_TIMEOUT_MS = 1000
