export const MESSAGE_DEFAULT_PRIORITY = null
export const MESSAGE_DEFAULT_NAME = null
export const MESSAGE_DEFAULT_NUM_ATTEMPTS = 1
export const MESSAGE_DEFAULT_LOCK_SECS = 60 * 5
export const MESSAGE_DEFAULT_LOCK_SECS_FACTOR = 2
export const MESSAGE_DEFAULT_PROCESSING_SECS = 60 * 60
export const MESSAGE_DEFAULT_DELAY_SECS = 0

export const DAEMON_PROCESSOR_DEFAULT_EXECUTION_SLOTS = 1
export const DAEMON_PROCESSOR_DEFAULT_TIMEOUT_SECS = 1
export const DAEMON_SCHEDULER_DEFAULT_TIMEOUT_SECS = 1
