name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - run: bun install

      - run: bun run lint
