name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - run: bun install

      - run: bun test --coverage

      - name: Upload code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: e7a50fab5135f11cac061309a73ccd8a2a8dd0d7ae583605758dcbe8d1a6b4a6
