name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - run: bun install

      - run: bun test --coverage
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Upload code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: e7a50fab5135f11cac061309a73ccd8a2a8dd0d7ae583605758dcbe8d1a6b4a6
